keys:
  - &users:
    - &n0ll age1nqmfr4wxlapuzlnw2xe52jazxgxymzfww7awah4t5xgdyk8mz4cqyeae5d
  - &hosts:
    - &nix-solid age19ulmwhz5j0v9xj5ajktzu9zq380yhkpwq0sdn53asua6kg88fvkqkn9h75
    - &nix-liquid age1g03kmn3v3mqgffk6yjl8r8hk4z3hs03pyq09lhc3ffgyvw6vsagsmlpy0g

creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - *n0ll
          - *nix-solid
          - *nix-liquid

  - path_regex: n0ll-secrets.yaml$
    key_groups:
      - age:
          - *n0ll
          - *nix-solid
          - *nix-liquid
