share:
    download_secret: your-secret-token
    download_window: 12
    password_salt: your-passwall-salt

upload:
    path: /upload
    maximum: 100GiB

# redis:
#     url: redis://015-redis:6379

features:
    file-share:
        enabled: true
    text-share:
        enabled: true
    file-image-compress:
        enabled: true
    file-image-convert:
        enabled: true

# 站点基本信息
site:
    url: http://localhost:31100
    title:
        'en': '015'
    desc:
        'en': '015 is an open-source temporary file sharing platform project that supports uploading, downloading, and sharing files and text.'
    icon: '/logo.png'
    bg_url: 'https://img.fudaoyuan.icu/api/1/random/?scale_min=1.5&webp=true&md=false&format=302'
    enable_bg: true

about:
    bg_url: 'https://files.mastodon.social/site_uploads/files/000/000/001/@1x/57c12f441d083cde.png'
    email: keven@fudaoyuan.icu
    name: keven
    avatar: ''
